In [1]:
import torch

In [2]:
x = torch.zeros(2,2)
x

tensor([[0., 0.],
        [0., 0.]])

In [3]:
x = torch.ones(2,2)
x

tensor([[1., 1.],
        [1., 1.]])

In [4]:
x = torch.randn(2,2)
x

tensor([[ 0.0346, -1.5248],
        [-2.1576,  1.1657]])

In [5]:
y = x + 10
y

tensor([[10.0346,  8.4752],
        [ 7.8424, 11.1657]])

In [6]:
dir(y)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ifloordiv__',
 '__ilshift__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rfloordiv__',
 '__rmul__',
 '__rpow__',
 '__rshift__',
 '__r

In [7]:
q = torch.zeros(2,2, requires_grad=True)
q

tensor([[0., 0.],
        [0., 0.]], requires_grad=True)

In [8]:
w = q + 10
w

tensor([[10., 10.],
        [10., 10.]], grad_fn=<AddBackward0>)

In [9]:
w.grad_fn