# TensorFlow Hello World

Tensor flow uses the commands as [graph](https://github.com/tensorflow/docs/blob/master/site/en/guide/intro_to_graphs.ipynb). This demo demonstrates this:

In [1]:
import tensorflow as tf

In [2]:
g = tf.Graph()

with g.as_default():
    operations = g.get_operations()
    print(operations)
    
    a = tf.compat.v1.constant(10, name='a')
    operations = g.get_operations()
    print(operations)
    
    b = tf.compat.v1.placeholder(tf.int32, name='b')
    operations = g.get_operations()
    print(operations)
    
    c = tf.multiply(a, b, name='c')
    operations = g.get_operations()
    print(operations)
    
    d = tf.add(c, 100, name='d')
    operations = g.get_operations()
    print(operations)
    
    # This values we need to pass to placeholder
    v_for_b = {b:[
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]}
    
    with tf.compat.v1.Session() as sess:
        result = sess.run(d, feed_dict=v_for_b)
print(result)    
    

[]
[<tf.Operation 'a' type=Const>]
[<tf.Operation 'a' type=Const>, <tf.Operation 'b' type=Placeholder>]
[<tf.Operation 'a' type=Const>, <tf.Operation 'b' type=Placeholder>, <tf.Operation 'c' type=Mul>]
[<tf.Operation 'a' type=Const>, <tf.Operation 'b' type=Placeholder>, <tf.Operation 'c' type=Mul>, <tf.Operation 'd/y' type=Const>, <tf.Operation 'd' type=Add>]
[[110 120 130]
 [140 150 160]
 [170 180 190]]
